### ISSUE TITLE
iPhone app?

### ISSUE THREAD

**Issue by hi-im-karma** [kawaiiDango/pScrobbler#363] opened 2023-08-18 14:44 UTC
I recently purchased my first ever iPhone. Now I'm using Android and iPhone. I was wondering if there are any plans for this wonderful, pretty PanoScrobbler app to be added to iOS? Would be amazing. All the current iOS scrobbler apps are ugly af.

**Comment by kawaiiDango** [comment] 2023-08-20 23:21
Duplicate of #95

**Closed** 2023-08-20 23:21 UTC
