### ISSUE TITLE
Latest update doesn't scrobble edited songs

### ISSUE THREAD

**Issue by Ryder9013** [kawaiiDango/pScrobbler#169] opened 2021-09-06 09:14 UTC
After the latest update (2.33 4 sept 21) after I edit any song that has been scrobbled, it disappears from the list and doesn't get scrobbled to last fm.

**Comment by kawaiiDango** [comment] 2021-09-06 14:28
Should be fixed in the next update

**Comment by Ryder9013** [comment] 2021-09-06 16:25
Now after updating it's not editing any song. The tick mark showing edit complete doesn't appear. And the song remains the same doesn't get edited.

**Comment by kawaiiDango** [comment] 2021-09-06 17:19
I cannot reproduce this issue. Can you show what you are trying to edit, before and after the edit?

**Comment by Ryder9013** [comment] 2021-09-06 17:35
Ok I was wrong about the tick not appearing. But the song remains the same even after tick.
![Screenshot_20210906-230448_Pano Scrobbler](https://user-images.githubusercontent.com/75566707/132249477-ab147820-84ba-411c-b3ad-64061c855916.jpg)
![Screenshot_20210906-230438_Pano Scrobbler](https://user-images.githubusercontent.com/75566707/132249470-24b3a199-c0f5-4a3b-9220-d4a970782fcc.jpg)

**Comment by kawaiiDango** [comment] 2021-09-07 16:50
Does this also happen on editing artist or the title?

**Comment by Ryder9013** [comment] 2021-09-07 18:24
Tried editing Artist on some song. It works. The Title of the song can't be edited though.

**Comment by Ryder9013** [comment] 2021-09-13 17:03
Now after latest update it works. But the app crashes as soon as editing is finished.

**Comment by oddtoddy** [comment] 2021-09-14 21:07
Latest update also crashes the app whenever you go into the configuration settings. It does this on multiple devices that I've tried.

**Closed** 2021-11-15 14:02 UTC
