### ISSUE TITLE
per app settings

### ISSUE THREAD

**Issue by RMHogervorst** [kawaiiDango/pScrobbler#347] opened 2023-06-19 05:45 UTC
**Is your feature request related to a problem, or particular use cases? Please describe.**
Pano scrobbler treats the radio station on somafm as album title. I wish I could guide the scrobbler by telling it what parts it should extract.

**Describe the solution you'd like**

**Additional info**

**Comment by kawaiiDango** [comment] 2023-06-19 11:22
Duplicate of #152

**Closed by kawaiiDango** 2023-06-19 11:22 UTC
Labels: enhancement
