### ISSUE TITLE
[Feature Request] Don't submit scrobble until song is no longer playing

### ISSUE THREAD

**Issue by aspensykes** [kawaiiDango/pScrobbler#203] opened 2022-02-09 00:05 UTC
Right now, with the "Submit now playing" toggle enabled, the current song gets scrobbled to Last.fm as soon as the scrobble delay is reached. I think it would be nice to have an option that only sends the scrobble to Last.fm when the song is no longer playing, while keeping the Now Playing feature functional.

For example:
- "Submit now playing" toggle enabled, scrobble delay set to whatever
- When the scrobble delay is reached, don't submit the scrobble yet if the song is still playing
- Once the song is over (finished/skipped), then assuming the scrobble delay has been met, submit to Last.fm

This would prevent songs from showing up twice while still playing after the scrobble delay - in this situation currently, two copies of the song are visible, the Now Playing one and the scrobbled one.

**Comment by Harmonie666** [comment] 2022-02-09 18:00
This would be a welcome change :)

**Comment by aspensykes** [comment] 2022-02-12 03:07
I don't think it looks terrible or anything, it's just a small enhancement that I think would be nice if possible, and I guess at least someone else agrees? Up to you at the end of the day.

It might be easier to add an option to simply stop the "Now playing" scrobble when the scrobble delay is reached, which would also work (albeit not quite as elegantly).

**Comment by nershman** [comment] 2022-02-28 00:47
Every scrobbler I've ever used has had the same scrobbling behavior as this one. I guess it doesn't hurt to add the option but this is just how scrobbling works.

**Comment by Harmonie666** [comment] 2022-02-28 00:50
Perhaps if the developer finds time and motivation he might add this option :)

**Comment by ReidZ3** [comment] 2022-03-31 04:01
> I don't think "two copies of the song" look that bad for this to be needed.

@kawaiiDango, it's not a matter of aesthetics — at least not for me. ***Pano Scrobbler*** was the first scrobbler I ever used. For the longest time, it confused me like crazy seeing two entries. Not to mention, I've had issues on occasion with duplicate scrobbles when using "Now playing" (mostly resolved), which has only served to exacerbate the problem.
The current UI causes unnecessary confusion. Until you know better, upon seeing two copies of the song to which you are currently listening, the natural reaction is to delete one of them — presuming the other to be a duplicate caused by a bug. Consequently, the scrobble is deleted from your history, and you become frustrated at the app.
Given the purpose of scrobblers as archival tools, this hardly seems like desirable behavior.

___

Regardless of user experience, this current implementation doesn't make much sense on its own.
Let's say you're listening to a playlist with 4 songs, simply entitled: `A`, `B`, `C`, and `D`. If you were listening to ***Spotify***, ***YouTube Music***, ***Amazon Music***, etc.; would it not throw you for a loop if opening your queue displayed something along the lines of:

|Queue|
|-|
|A|
|B|
|C|
|**C   `⏮ ⏯ ⏭`** 3:08 / 4:42 <br /> ─────────⚪───── |
|D|

That is essentially what the current behavior does.
I don't understand the benefit to preserving this inconsistency between scrobbler and music player.

___

To be clear, however, I do not think that the solution proposed by @aspensykes is a reasonable one.
I suggest instead that the most recent scrobble be hidden while it's song is still playing. I haven't had the chance to skim through the code yet, but I assume that if a song is currently being played it is cached or stored in some way to prevent multiple scrobbles from one song. So, unless I'm overlooking something, it should be a relatively trivial change.

**Comment by ReidZ3** [comment] 2022-03-31 04:09
https://github.com/kawaiiDango/pScrobbler/issues/203#issuecomment-1084048640 — Tl;dr:
Two seemingly duplicate copies in scrobbles is confusing & has caused scrobbles to be unintentionally deleted. Incongruous with music players' universal behavior.
New proposed solution — hide actual scrobble from list until "Now playing" scrobble entry finishes. Resolves initial problem with a simpler solution.

**Comment by relampo** [comment] 2022-04-02 11:19
> Every scrobbler I've ever used has had the same scrobbling behavior as this one.

That's weird because I don't recall any other app doing this? And I've been scrobbling for a long time... Nowadays I use [foo_scrobble](https://github.com/gix/foo_scrobble) and Spotify's own integrated scrobbling feature, and none of them display this behaviour. IMO it's a bug.
Maybe we could do it like foo_scrobble does it? If that's at all possible

**Comment by aspensykes** [comment] 2022-04-03 03:15
> That's weird because I don't recall any other app doing this? And I've been scrobbling for a long time... Nowadays I use [foo_scrobble](https://github.com/gix/foo_scrobble) and Spotify's own integrated scrobbling feature, and none of them display this behaviour.

This is more or less where I'm coming from - I've used both Spotify's and Tidal's built-in scrobbling, as well as the very popular [Web Scrobbler project](https://github.com/web-scrobbler/web-scrobbler), and all of them only submit a scrobble to Last.fm when the track is no longer playing. From what I've seen, this is a fairly standard feature on a lot of Last.fm scrobblers.

**Comment by jonpsp** [comment] 2022-04-03 10:50
When I use Web Scrobbler, it submits the scrobble when the song has reached the minimum duration. Until then, the song appears in my Last.fm "Recent Tracks" view as "Now Scrobbling". It doesn't wait until the song has finished playing. After the song has been scrobbled, whilst it is still playing it appears twice on last.fm. 
For me, Web Scrobbler behaves like Pano Scrobbler.

**Comment by aspensykes** [comment] 2022-04-03 17:07
> When I use Web Scrobbler, it submits the scrobble when the song has reached the minimum duration. Until then, the song appears in my Last.fm "Recent Tracks" view as "Now Scrobbling". It doesn't wait until the song has finished playing. After the song has been scrobbled, whilst it is still playing it appears twice on last.fm. For me, Web Scrobbler behaves like Pano Scrobbler.

You're right, sorry - I got it mixed up with [the official Last.fm scrobbler](https://www.last.fm/about/trackmymusic) which *does* only submit tracks when they're done playing.

**Comment by kawaiiDango** [comment] 2022-05-15 11:54
Closing as I will not be implementing this

**Closed by kawaiiDango** 2022-05-15 11:54 UTC
