### ISSUE TITLE
Different sponsor methods

### ISSUE THREAD

**Issue by lostb053** [kawaiiDango/pScrobbler#362] opened 2023-08-16 22:05 UTC
So i couldn't use normal sponsor method (Google PlayStore), idk why (system isn't running in indian region, maybe that's why, or a bug). But I'm still interested in premium version. I noticed you have a ko-fi account, so wondered if i can pay you 3$ (equivalent to around 250 inr), and still get the premium on playstore (like bound with email id)

In the mean time, consider this a feature request (I'll open a new issue as feature request if u agree to it), i use this music player called Stellio Music player. It allows you to bind "out of playstore bought premium" to your email id. So you don't have to use code (they use activation code) or any other hassle again and again. Maybe add that (hope I'm clear enough)? I don't know if it already works like that, given I'm unable to get it atm 🙂

My question is not listed in the FAQ at https://telegra.ph/Pano-Scrobbler-FAQ-05-30

**Comment by kawaiiDango** [comment] 2023-08-21 06:28
Duplicate of #229

There are no plans to implement this as of now.

By the way, the ko-fi account is linked to my PayPal. Since PayPal does not allow domestic transactions in India due to govt orders, that payment won't go through either.

**Closed** 2023-08-21 06:29 UTC
Labels: question
