### ISSUE TITLE
Sometimes, after pausing a song, the scrobble is not complete

### ISSUE THREAD

**Issue by theruleof4** [kawaiiDango/pScrobbler#132] opened 2021-05-04 21:24 UTC
I have noticed this for a while when a song is playing and for some reason, you pause it, either to watch a video, or answer a call, when playing again, the app does not detect the song again, even if it was paused on the beginning of the song, and then listen to the rest of it, the app does not detect (does not appear in the notification bar) and the scrobble is not done, then, when the next song starts it detects normally, but the one that was paused does not.

**Comment by kawaiiDango** [comment] 2021-05-05 10:20
Cannot reproduce this. Songs once scrobbled will not be scrobbled again
unless it is played on repeat, if that's what you are talking about.

**Comment by theruleof4** [comment] 2021-05-05 11:14
No, its not ths way. When I pause a song, the scrobbler was done yet, and when I resume the song, the app do not recognize anymore, so the scrobble is not complete.

**Comment by kawaiiDango** [comment] 2021-05-05 19:04
Send a bug report from the app shortly after the issue happens

**Comment by theruleof4** [comment] 2021-05-06 22:16
Here the log
`--------- beginning of main
05-06 07:21:08.918 14931 14931 I scrobbler: onPlaybackStateChanged=3 laststate=3 pos=0 duration=388000 cb=249835366
05-06 07:21:08.919 14931 14931 I scrobbler: playing: timePlayed=0 Speed + Sound (Endless)
05-06 07:21:08.926 14931 19222 I scrobbler: scrobble np Sandwell District - Speed + Sound (Endless)
05-06 07:21:09.414 14931 14931 I scrobbler: onMetadataChanged Sandwell District (Sandwell District) [Feed-Forward] ~ [Untitled], sameAsOld=false, lastState=3, package=com.kodarkooperativet.blackplayerex cb=249835366
05-06 07:21:09.418 14931 21643 I scrobbler: scrobble np Sandwell District - [Untitled]
05-06 07:21:09.563 14931 14931 I scrobbler: onPlaybackStateChanged=3 laststate=3 pos=0 duration=382000 cb=249835366
05-06 07:21:11.436 14931 14943 W ble:bgScrobble: Reducing the number of considered missed Gc histogram windows from 103 to 100
05-06 07:21:39.433 14931 21643 I scrobbler: scrobble submit Sandwell District - [Untitled]
05-06 07:22:29.687 25697 25697 W ocess.gservices: type=1400 audit(0.0:1040495): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=22858 scontext=u:r:priv_app:s0:c743,c771 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0
05-06 07:23:42.432 14931 14931 I scrobbler: onPlaybackStateChanged=2 laststate=3 pos=152592 duration=382000 cb=249835366
05-06 07:23:42.432 14931 14931 I scrobbler: -781755960 cancelled
05-06 07:23:42.433 14931 14931 I scrobbler: paused
05-06 07:24:36.082 14931 14931 I scrobbler: onMetadataChanged Sandwell District (Sandwell District) [Feed-Forward] ~ [Untitled], sameAsOld=true, lastState=2, package=com.kodarkooperativet.blackplayerex cb=249835366
05-06 07:24:36.177 14931 14931 I scrobbler: onPlaybackStateChanged=3 laststate=2 pos=152592 duration=382000 cb=249835366
05-06 07:24:44.685 30053 30053 E om.arn.scrobbl: Not starting debugger since process cannot load the jdwp agent.
05-06 07:24:44.804 30053 30053 W om.arn.scrobbl: JIT profile information will not be recorded: profile file does not exits.
05-06 07:24:44.804 30053 30053 I chatty  : uid=10214(com.arn.scrobble) identical 365 lines
05-06 07:24:44.804 30053 30053 W om.arn.scrobbl: JIT profile information will not be recorded: profile file does not exits.
05-06 07:24:44.812 30053 30053 I Perf    : Connecting to perf service.
05-06 07:24:44.845 30053 30053 I FeatureParser: can't find pyxis.xml in assets/device_features/,it may be in /system/etc/device_features
05-06 07:24:44.847 30053 30053 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
05-06 07:24:44.880 30053 30053 W scrobbler_time: : [1620296684880] onCreate start
05-06 07:24:44.900 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:44.904 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:44.931 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:44.936 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:44.939 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:44.940 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:44.941 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:44.941 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:44.943 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:44.952 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:44.954 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:44.957 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:44.958 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:44.958 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:44.962 30053 30053 W scrobbler_time: : [82] onCreate setContentView
05-06 07:24:44.981 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.001 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.005 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.007 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.007 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.012 30053 30080 E Perf    : Fail to get file list com.arn.scrobble
05-06 07:24:45.012 30053 30080 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
05-06 07:24:45.012 30053 30080 E Perf    : Fail to get file list oat
05-06 07:24:45.013 30053 30080 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
05-06 07:24:45.017 30053 30053 W scrobbler_time: : [55] onPostCreate
--------- beginning of system
05-06 07:24:45.035 30053 30053 W Looper  : Slow Looper main: Activity com.arn.scrobble/.Main is 328ms late (wall=0ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 3 msg, msg 2 took 141ms (seq=2 running=62ms runnable=15ms io=54ms late=6ms h=android.app.ActivityThread$H w=110), msg 3 took 185ms (seq=3 running=114ms runnable=37ms io=12ms reclaim=4ms late=143ms h=android.app.ActivityThread$H w=159)
05-06 07:24:45.036 30053 30053 I scrobbler: ensureServiceRunning service - pid: 14931, currentPID: 30053, clientPackage: android, clientCount: 1 process:com.arn.scrobble:bgScrobbler, clientLabel: (Ouvinte de notificações)
05-06 07:24:45.056 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.056 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.057 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.064 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.070 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.077 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.078 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.080 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.086 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.089 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.091 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.093 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.095 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.103 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.107 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.109 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.111 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.117 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.118 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.120 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.121 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.122 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.123 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.123 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.128 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.130 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.134 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.152 30053 30126 I scrobbler: getRecents 1
05-06 07:24:45.162 30053 30081 I AdrenoGLES: QUALCOMM build                   : 8c08135, I8fa107637b
05-06 07:24:45.162 30053 30081 I AdrenoGLES: Build Date                       : 10/22/20
05-06 07:24:45.162 30053 30081 I AdrenoGLES: OpenGL ES Shader Compiler Version: EV031.27.05.01
05-06 07:24:45.162 30053 30081 I AdrenoGLES: Local Branch                     : 
05-06 07:24:45.162 30053 30081 I AdrenoGLES: Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.8.8.R1.10.00.00.545.051
05-06 07:24:45.162 30053 30081 I AdrenoGLES: Remote Branch                    : NONE
05-06 07:24:45.162 30053 30081 I AdrenoGLES: Reconstruct Branch               : NOTHING
05-06 07:24:45.162 30053 30081 I AdrenoGLES: Build Config                     : S P 8.0.11 AArch64
05-06 07:24:45.165 30053 30053 W RecyclerView: No adapter attached; skipping layout
05-06 07:24:45.166 30053 30053 W RecyclerView: No adapter attached; skipping layout
05-06 07:24:45.167 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.167 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.168 30053 30081 I AdrenoGLES: PFP: 0x016ee18a, ME: 0x00000000
05-06 07:24:45.168 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.170 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.170 30053 30081 W AdrenoUtils: <ReadGpuID_from_sysfs:198>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
05-06 07:24:45.170 30053 30081 W AdrenoUtils: <ReadGpuID:222>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
05-06 07:24:45.171 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.174 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.176 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.176 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.178 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.183 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.193 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.203 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.204 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.206 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.207 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.209 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.210 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.211 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.213 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.218 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.232 30053 30081 W Gralloc3: mapper 3.x is not supported
05-06 07:24:45.288 30053 30081 E LB      : fail to open file: No such file or directory
05-06 07:24:45.317 30053 30126 I scrobbler: getRecents 1
05-06 07:24:45.321 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.324 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.325 30053 30126 D NetworkSecurityConfig: No Network Security Config specified, using platform default
05-06 07:24:45.327 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.330 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.345 30053 30157 I scrobbler: getHeroInfo
05-06 07:24:45.354 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.355 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.355 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.356 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.356 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.357 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.358 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.359 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.376 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.385 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.385 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.391 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.391 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.396 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.397 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.398 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.401 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.402 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.403 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.403 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.404 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.404 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.412 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.415 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.416 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.417 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.417 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.418 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.436 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.436 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.439 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:45.439 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.101 30053 30233 W BpBinder: Slow Binder: BpBinder transact took 229 ms, interface=com.android.vending.billing.IInAppBillingService, code=1 oneway=false
05-06 07:24:46.591 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.596 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.596 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.598 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.599 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.602 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.602 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.602 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.603 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.606 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.612 30053 30126 I scrobbler: getHeroInfo
05-06 07:24:46.612 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.651 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.651 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.652 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.652 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.653 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.656 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.656 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.657 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.658 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.659 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.660 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.673 30053 30053 D ForceDarkHelper: updateByCheckExcludeList: pkg: com.arn.scrobble activity: com.arn.scrobble.Main@8d6e3f8
05-06 07:24:46.758 30053 30068 W System  : A resource failed to call close. 
05-06 07:24:47.134 30053 30244 W BpBinder: Slow Binder: BpBinder transact took 1018 ms, interface=com.android.vending.billing.IInAppBillingService, code=901 oneway=false
05-06 07:24:48.208 30053 30081 W RenderInspector: DequeueBuffer time out on com.arn.scrobble/com.arn.scrobble.Main, count=1, avg=18 ms, max=18 ms.
05-06 07:24:50.150 30053 30126 I scrobbler: getDrawerInfo
05-06 07:24:55.635 30053 30053 I scrobbler: ensureServiceRunning service - pid: 14931, currentPID: 30053, clientPackage: android, clientCount: 1 process:com.arn.scrobble:bgScrobbler, clientLabel: (Ouvinte de notificações)
`

**Comment by kawaiiDango** [comment] 2021-05-07 07:54
According to the log, Sandwell District - [Untitled] was scrobbled before
it was paused. Is that what happened? Are you scrobbling offline?

**Comment by kawaiiDango** [comment] 2021-05-12 14:34
Closing as the logs do not reflect what you said.

**Closed by kawaiiDango** 2021-05-12 14:34 UTC
