### ISSUE TITLE
can you submit this app to fdroid?

### ISSUE THREAD

**Issue by zombiehoffa** [kawaiiDango/pScrobbler#216] opened 2022-04-12 19:05 UTC
This would be really awesome for those of us avoiding the google apps store.

**Comment by airon90** [comment] 2022-04-14 11:55
Duplicate of #2

**Comment by zombiehoffa** [comment] 2022-04-14 13:20
> Duplicate of #2

Sorry, I didn't search closed issues. If you are unable to add this to fdroid can you at least create a repo for your app that I can add to f-droid? Here is an example of how someone did this directly on github:
https://ikas-mc.github.io/fdroid-repo/
https://github.com/ikas-mc/fdroid-repo

**Comment by kawaiiDango** [comment] 2022-04-14 14:35
Why not just use aurora store?

**Comment by Efreak** [comment] 2022-04-14 16:06
Use of Aurora store doesn't avoid the Google store. Quite the opposite, really. It only avoids the Google play app, it still connects to Google servers. If you've blocked access to those servers, then it won't work. (Personally, I think this is overkill, but I believe some people actually do so). It also leaves you dependent of Google like before, and still requires a Google account for some functionality (paid apps, betas, etc). For those trying to remove Google from their life entirely, this is a big no.

**Comment by zombiehoffa** [comment] 2022-04-14 16:26
> Use of Aurora store doesn't avoid the Google. Quite the opposite, really. It only avoids the Google play app, it still connects to Google servers. If you've blocked access to those servers, then it won't work. (Personally, I think this is overkill, but I believe some people actually do so). It also leaves you dependent of Google like before, and still requires a Google account for some functionality (paid apps, betas, etc). For those trying to remove Google from their life entirely, this is a big no.

yep, which is what I am trying to do because it is bonkers how much those guys spy on you (sending hashes of my text messages, really google?????) I shouldn't have waited for them to get rid of free legacy google apps to prompt me to move, I should have moved away years ago. 

If you wanted to be even awesomer you could make the google apps version cost a buck or two while providing the f-droid repository for free. That would help fund your project for people who can't be bothered to setup fdroid while helping drive adoption of a google free alternative.

**Comment by zombiehoffa** [comment] 2022-04-14 17:27
> I won't be maintaining second variant without Google dependencies if that's what you are asking.

I am asking you to please provide an f-droid repository I can add to my f-droid app to deliver your app(s). microg makes your google dependencies work with an adequate amount of privacy from google. This is basically similar to what you are doing now posting the apk in the releases on github but it makes the update process for that automated for your users.

I was suggesting that an extra thing you could do was make your google apps version cost some small amount of money while keeping your f-droid repository and github apks free, as that would have a two pronged effect of generating funding for your project while also incentivizing more people towards a freer and more private alternative. This was just a suggestion though, you may have any number of personal reasons to not do the above and those are all perfectly reasonable, as this is your project do with with as you please.

**Comment by kawaiiDango** [comment] 2022-04-14 19:44
If automating updates if the issue, I could implement an in app updater which would run if it cannot find the play Store app. It would also work for people who directly downloaded the apk from the readme or elsewhere, without needing to install fdroid or having to know what the repo url is.

**Closed** 2022-05-15 11:23 UTC

**Comment by kawaiiDango** [comment] 2022-05-15 20:18
The minimal update notifier will only be visible if it does not find Play Store on your device and will open the download url in a browser as Google is trying to restrict the install apps permission

**Comment by kawaiiDango** [comment] 2024-03-10 17:40
I created an F-droid repo now (see readme), since the in-app update checker will be removed in the next release, just to be safe, as apps on Play Store shouldn't try to update themselves from sources other than Play Store.

The entire F-droid repo gets dynamically created on github pages every time a new github release is uploaded. I haven't seen anyone do it like this, so let me know if repo breaks between updates.
