### ISSUE TITLE
Scrobbles don't log while Chromecasting with the screen off.

### ISSUE THREAD

**Issue by peepincreepin** [kawaiiDango/pScrobbler#147] opened 2021-06-27 12:46 UTC
Ver: Pano Scrobbler v2.26 - 17.Jun.21
OS: Android 11
Device: samsung SM-A515F / a51

When I'm casting from my phone to any of my Google devices, Pano sends the 'Now Playing' song to last.fm, but if my screen is off, it doesn't actually save the scrobble. I had the exact same issue on my old phone (Nokia 7+ running Anroid 10 and below). I've tried uninstalling and reinstalling Pano; logging in and out of last.fm; changing Pano notifications from Silent to Alerting; turning on/off lockscreen notifications ... at best it starts working for a few songs but then stops again. My workaround has been to set my display to never sleep, but obviously that's not great for battery conservation and I have to remember to turn it on and off every time.

I initially assumed this issue applied to all scrobbling apps, but recently realised that the Scroball app works and saves scrobbles while casting. I think the issue _might_ be that Scroball has both "Now Playing" and "Scrobbled" notifications, whereas Pano only has a "Now Playing" one. So Pano submits the "Now Playing" song, but doesn't actually log the scrobble. I'm not sure _why_ that causes an issue when the screen is off, on some phones but not others. Here is a reddit thread on the issue: https://www.reddit.com/r/YoutubeMusic/comments/o67vnh/pano_scrobbler_google_home_and_newer_android/

Obviously I could just switch to using Scroball, but I much prefer Pano overall (apart from this one issue), so I'm hoping that this is something that can be fixed

**Comment by kawaiiDango** [comment] 2021-06-28 05:17
Does this also happen with other apps while casting? I have never tested
this app with a chromecast device as I don't own one.

**Comment by peepincreepin** [comment] 2021-06-28 05:36
> Does this also happen with other apps while casting? I have never tested this app with a chromecast device as I don't own one.

Just with Pano, as far as I know. I've just tried Scroball and the official Last.fm app, and they both log scrobbles fine while casting with the screen off.

**Comment by kawaiiDango** [comment] 2021-06-28 11:09
I mean apps that play music and cast

**Comment by peepincreepin** [comment] 2021-06-28 22:31
Oh I see, apologies for the misunderstanding!

Yes, this seems to also happen on Pano when casting with other streaming apps. I have just tested Spotify and Deezer, and the same thing happens: the Now Playing song comes through on last.fm, but the actual logging is unstable, and scrobbles are not saved.

**Comment by kawaiiDango** [comment] 2021-06-29 15:06
Check if this works https://transfer.sh/1DzSKyC/pScrobbler-release.apk

**Comment by peepincreepin** [comment] 2021-06-29 21:03
Thanks for the quick response! :)

So it scrobbles some tracks but misses others now when casting with the screen off. However now it's doing the same and randomly missing out some tracks when casting with the screen on, and also when not casting at all. 🤣

**Comment by kawaiiDango** [comment] 2021-06-29 22:52
Reproduce this issue and then send a bug report from the app soon after.
Also mention the times at which screen was turned off and on, and the songs
which should have been scrobbled but weren't.

**Comment by peepincreepin** [comment] 2021-06-30 00:17
Done!

**Comment by kawaiiDango** [comment] 2021-07-02 15:52
Youtube music puts the duration of the previous song and some time later puts the correct duration, which gets discarded by pano as a duplicate. Some of the songs were not scrobbled because a longer song was played before it. Also the app was freezing when it got disconnected from google play services, causing it to skip scrobbles at those times.

Check if this works https://transfer.sh/1aLzQhc/pScrobbler-release.apk

**Comment by kawaiiDango** [comment] 2021-07-02 16:12
Youtube music puts the duration of the previous song and some time later puts the correct duration, which gets discarded by pano as a duplicate. Some of the songs were not scrobbled because a longer song was played before it. Also the app was freezing when it got disconnected from google play services, causing it to skip scrobbles at those times.

Check if this works https://transfer.sh/1Rmfj7D/pScrobbler-release.apk

Discard the previous message. I posted the wrong link.

**Comment by peepincreepin** [comment] 2021-07-04 20:37
Sorry for the late response! I've just tested it and it's definitely performing much better than before. It's still skipping a few songs, though. I've just sent a bug report about it. Thanks again for your support on this.

**Comment by kawaiiDango** [comment] 2021-07-11 06:55
Did you manage to get a proper log?

**Comment by kawaiiDango** [comment] 2021-07-19 07:10
Check if this is fixed in the latest update (Download the apk from the readme, or wait till google approves the update in play store)

**Comment by peepincreepin** [comment] 2021-07-21 08:40
It doesn't work, unfortunately; I've sent another bug report.

**Comment by kawaiiDango** [comment] 2021-07-22 13:33
Try this https://transfer.sh/1zMJGBa/pScrobbler-release.apk

This probably doesnt fix anything, but it logs reasons why the scrobbler service is still freezing and restarting.

**Comment by kawaiiDango** [comment] 2021-09-05 13:25
Did you manage to get logs?

**Comment by kawaiiDango** [comment] 2021-09-07 16:51
I think this is not an issue with the app. Something external may be trying to kill the scrobbler and it restarts because the scrobbler is sticky.

This is just my guess. I haven't tested it with Chromecast as a I don't have one.

**Closed by kawaiiDango** 2021-09-07 16:51 UTC

**Comment by austinbutler** [comment] 2022-01-07 02:40
Same problem here. I know this issue is closed, but adding some more info in case it's useful to anyone that finds this.

Tried setting Pano to "unrestricted" battery in Android settings, didn't fix it. Also tried enabling the lock screen notification for Pano, again no go.

To my surprise the official Last.fm app seems to work with the screen off without any special battery settings or anything. The "now playing" can be more hit or miss though, which with Pano seemed pretty reliable. It's like they are inverted that way.
