### ISSUE TITLE
Title of the song automatically removes (feat. Artist)

### ISSUE THREAD

**Issue by Ryder9013** [kawaiiDango/pScrobbler#158] opened 2021-08-18 13:14 UTC
Whenever I'm listening to a song which has "Song Name (feat. Artist)" in the song name, Pano Scrobbler automatically changes it to "Song Name". I do have Pattern edit for removing "(feat. Artist)" enabled but that's enabled for Artist field not the Track field. I think it's because of the (Explicit) pattern edit in Track field. Maybe you can tell me how to edit it to only remove (Explicit) from the field and not (feat.)

**Comment by kawaiiDango** [comment] 2021-08-20 05:05
I cannot reproduce this. Please provide your settings backup file and the link to the song which causes this issue.

**Comment by Ryder9013** [comment] 2021-08-20 08:23
Sure.
Check out No Joke (feat. Ab Soul) [Explicit] by Jay Rock on Amazon Music
https://music.amazon.in/albums/B016XD1NMG?trackAsin=B016XD1SRG&ref=dm_sh_Ja9l3nIxwuarNhetU1boNH4Px 
https://drive.google.com/file/d/1OZbrIHqqhDGG4LhWApKARErn-6Pgc2v3/view?usp=sharing - Backup of Settings

**Comment by Ryder9013** [comment] 2021-08-20 08:23
I scrobble the above song it gets scrobbled as "No Joke". I believe Explicit pattern edit removes all other stuff as well.

**Comment by kawaiiDango** [comment] 2021-08-21 16:08
Looks like the explicit pattern removes other brackets and not the feat pattern. Can you confirm by deleting the explicit patterns?

**Comment by Ryder9013** [comment] 2021-08-22 01:18
Removed the "Explicit (Track)" pattern edit. Now it gets scrobbled as No Joke (feat. Ab Soul) [Explicit]. So I think I am right about Explicit pattern edit removing the (feat.) part too.

**Comment by Ryder9013** [comment] 2021-08-24 13:18
Same thing is happening in case of Album (Explicit) pattern edit. If I am listening to "It Was Written (Expanded Edition) [Explicit]" it gets scrobbled as "It Was Written"

**Comment by kawaiiDango** [comment] 2021-09-04 23:28
This should be fixed in the next update

**Closed by kawaiiDango** 2021-09-04 23:28 UTC
