### ISSUE TITLE
Album Artist Is Not Scrobbled

### ISSUE THREAD

**Issue by UserNo84** [kawaiiDango/pScrobbler#288] opened 2022-11-28 08:03 UTC
Hi!

I actually made a GitHub account only to report this issue. I already mentioned this in a Google Play Store review but stuff usually gets ignored there.

What's the issue? Well, Pano Scrobbler seems to ignore the "albums artist" field when scrobbling. Example:  
![Screenshot (21)](https://user-images.githubusercontent.com/119287715/204223068-762e1d18-8200-40f7-b3ab-e43a0fac5996.png)

As you can see, this track is part of the soundtrack to "Mission Impossible 2". The entire CD consists of 17 tracks by 17 different artists. _Various Artists_ is therefor the logical album artist. When playing this album with the official scrobbler, all tracks will count towards this album:
https://www.last.fm/music/Various+Artists/Music+From+And+Inspired+By+Mission:+Impossible+2

That's the way it should be. Pano Scrobbler, however, ignores the _Various Artists_ tag and uses the track artist instead, creating wrong albums and messing up the stats.

![Screenshot (22)](https://user-images.githubusercontent.com/119287715/204226473-582678f7-c869-433d-8e74-ca1d219b6199.png)

Instead of scrobbling the above album 17 times, it scrobbles 17 differents albums – one for each track artist. Example:
https://www.last.fm/music/Limp+Bizkit/Music+From+And+Inspired+By+Mission:+Impossible+2

Why? This issue is the only reason why I still use the ancient desktop scrobbler and the only reason why I didn't purchase the app so far. Some might find this petty and irrelevant but this issue creates bad data and messes up stats.

I really hope this will be fixed soon. It's the only negative thing about an otherwise fantastic app! 👍

**Comment by kawaiiDango** [comment] 2022-11-28 09:19
duplicate of https://github.com/kawaiiDango/pScrobbler/issues/227

**Closed** 2022-11-29 00:06 UTC
