### ISSUE TITLE
[Feature Request] For Scrobbling from SomaFM - The ability to pattern edit by taking info from one field and moving it to another.

### ISSUE THREAD

**Issue by genericuser100** [kawaiiDango/pScrobbler#361] opened 2023-08-08 08:34 UTC
**Is your feature request related to a problem, or particular use cases? Please describe.**
This is a particular use case: I would like to use PanoScrobbler with SomaFM's app on Android. The issue is, the scrobbles parse to last.fm with the "radio station" as the [artist], and the "artist - track name" as the [track name]. See [this image](https://i.imgur.com/geKZ1CX.jpg) for an example.

**Describe the solution you'd like**
A way to pattern edit everything before the hyphen and replace the artist name, and perhaps more generally, take info from one field and place it in another. Or just a solution to this particular scrobbling from SomaFM. Although I appreciate that one of the solutions might a bit out of the scope of PanoScrobbler and could be more in the ballpark of the devs from the SomaFM app.

**Additional info**
WebScrobbler on desktop Windows works fine for SomaFM's website. I've also tried listening through some browsers on Android (Chrome & Brave) but they don't scrobble at all (the info they seem to parse is just the radio station).

**Comment by kawaiiDango** [comment] 2023-08-09 03:28
Duplicate of https://github.com/kawaiiDango/pScrobbler/issues/152

**Closed** 2023-08-09 08:47 UTC
Labels: enhancement
